修改tieba.py,完成
HairlessVillager/minehotspot pull request #3
Opened 2024-07-02 06:54 UTC by BzcLoveXrn

2024-07-02 08:07 UTC, HairlessVillager commented
@BzcLoveXrn resolve conflicts

2024-07-03 03:13 UTC, HairlessVillager commented
@BzcLoveXrn resolve conflicts

2024-07-03 09:04 UTC, HairlessVillager requested changes
#4 #5 都没修？

2024-07-03 09:04 UTC, HairlessVillager commented on scrapy/minehotspot/spiders/tieba.py
> +            yield replace(item, text=text, time=time_
补上右括号

2024-07-03 11:44 UTC, BzcLoveXrn commented on scrapy/minehotspot/spiders/tieba.py
> +            yield replace(item, text=text, time=time_
##右括号补好了，parse_detail()加入了uid即 #4，floor字段正在处理ing

2024-07-04 01:58 UTC, HairlessVillager requested changes
#5 没修

2024-07-04 05:33 UTC, HairlessVillager commented
[6f0e668](https://github.com/HairlessVillager/minehotspot/pull/3/commits/6f0e668ca085ad25d4d14d0bdc709ed326e48be2) 单独拉一个分支做pr

2024-07-04 05:33 UTC, closed without merging